# Generated by Django 3.2.25 on 2025-02-04 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0032_auto_20250121_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics'),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 12, 43, 58, 914051)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 12, 43, 58, 914051)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionA_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionB_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionC_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics'),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='optionD_image',
            field=models.ImageField(blank=True, null=True, upload_to='faculty_profile_pics'),
        ),
    ]
