# Generated by Django 3.2.25 on 2025-01-21 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0031_auto_20250121_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_db',
            name='optionA_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionB_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionC_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='question_db',
            name='optionD_image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 11, 15, 19, 692448)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 11, 15, 19, 692448)),
        ),
    ]
